// Angular/adminpro/src/app/auth/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { User } from '../../shared/interfaces/user';
import { AuthService } from '../../shared/services/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
  providers: [AuthService],
})
export class RegisterComponent implements OnInit {
  // Variable para registrar al usuario
  public user: User;
  // Variables auxiliares para el formulario de registro
  nombre: string;
  email: string;
  password: string;
  passwordConfirm: string;
  acceptTerms: Boolean;

  constructor(private authService: AuthService, private router: Router) {}

  ngOnInit(): void {}

  onSubmit() {
    if(this.email == "" || this.nombre == "" || this.password == "" || this.passwordConfirm == ""){
      alert('No pueden haber campos vacios');
      return;
    }
    if (this.password != this.passwordConfirm) {
      alert('No coinciden las contraseñas');
      return;
    }
    if (!this.acceptTerms) {
      alert('No ha aceptado los terminos');
      return;
    }

    this.authService.getOneUserData(this.email).subscribe((response) => {
      if (response) {
        // Redirigir al login
        alert('El usuario indicado ya existe');
      } else {
        // Si coinciden las contraseñas
        this.user = {
          Nombre: this.nombre,
          Email: this.email,
          Password: this.password,
        };

        // Agregar al usuario
        this.authService.addUser(this.user).subscribe((response) => {
          if (response.status == 200) {
            // Redirigir al login
            this.router.navigate(['/login']);
          }
        });
      }
    });
  }
}

<section id="wrapper" class="login-register login-sidebar" style="background-image:url(../assets/images/background/login-register.jpg);">
  <div class="login-box card">
      <div class="card-body">
          <form class="form-horizontal form-material" id="loginform"> <!--</form> action="index.html"> -->
              <a href="javascript:void(0)" class="text-center db"><img src="../assets/images/logo-icon.png" alt="Home" /><br/><img src="../assets/images/logo-text.png" alt="Home" /></a>
              <h3 class="box-title m-t-40 m-b-0">Register Now</h3><small>Create your account and enjoy</small>
              <div class="form-group m-t-20">
                  <div class="col-xs-12">
                      <input class="form-control" type="text" [(ngModel)]="nombre" name="nombre" required placeholder="Name">
                  </div>
              </div>
              <div class="form-group ">
                  <div class="col-xs-12">
                      <input class="form-control" type="text" [(ngModel)]="email" name="email" required placeholder="Email">
                  </div>
              </div>
              <div class="form-group ">
                  <div class="col-xs-12">
                      <input class="form-control" type="password" [(ngModel)]="password" name="password" required placeholder="Password">
                  </div>
              </div>
              <div class="form-group">
                  <div class="col-xs-12">
                      <input class="form-control" type="password" [(ngModel)]="passwordConfirm" name="passwordConfirm" required placeholder="Confirm Password">
                  </div>
              </div>
              <div class="form-group row">
                  <div class="col-md-12">
                      <div class="checkbox checkbox-primary p-t-0">
                          <input id="checkbox-signup" type="checkbox" [(ngModel)]="acceptTerms" name="acceptTerms">
                          <label for="checkbox-signup"> I agree to all <a href="#">Terms</a></label>
                      </div>
                  </div>
              </div>
              <div class="form-group text-center m-t-20">
                  <div class="col-xs-12">
                      <button class="btn btn-info btn-lg btn-block text-uppercase waves-effect waves-light" type="button" (click)="onSubmit()">Sign Up</button>
                  </div>
              </div>
              <div class="form-group m-b-0">
                  <div class="col-sm-12 text-center">
                      <p>Already have an account? <a routerLink="/login" class="text-info m-l-5"><b>Sign In</b></a></p>
                  </div>
              </div>
          </form>
      </div>
  </div>
</section>

// Vue/dashboardvue/src/components/auth/RegisterComponent.vue
<template>
    <section id="wrapper" class="login-register login-sidebar" style="background-image:url(/assets/images/background/login-register.jpg);">
        <div class="login-box card">
            <div class="card-body">
                <form class="form-horizontal form-material" id="loginform" action="index.html">
                    <a href="javascript:void(0)" class="text-center db"><img src="/assets/images/logo-icon.png" alt="Home" /><br/><img src="/assets/images/logo-text.png" alt="Home" /></a>
                    <h3 class="box-title m-t-40 m-b-0">Register Now</h3><small>Create your account and enjoy</small>
                    <div class="form-group m-t-20">
                        <div class="col-xs-12">
                            <input class="form-control" type="text" required="" placeholder="Name">
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input class="form-control" type="text" required="" placeholder="Email">
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input class="form-control" type="password" required="" placeholder="Password">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <input class="form-control" type="password" required="" placeholder="Confirm Password">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <div class="checkbox checkbox-primary p-t-0">
                                <input id="checkbox-signup" type="checkbox">
                                <label for="checkbox-signup"> I agree to all <a href="#">Terms</a></label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group text-center m-t-20">
                        <div class="col-xs-12">
                            <button class="btn btn-info btn-lg btn-block text-uppercase waves-effect waves-light" type="submit">Sign Up</button>
                        </div>
                    </div>
                    <div class="form-group m-b-0">
                        <div class="col-sm-12 text-center">
                            <p>Already have an account? <a href="pages-login-2.html" class="text-info m-l-5"><b>Sign In</b></a></p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
</template>


<style scoped>
.login-register {
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center center;
  height: 100%;
  width: 100%;
  padding: 10% 0;
  position: fixed;
}

.login-box {
  width: 400px;
  margin: 0 auto;
}
.login-box .footer {
  width: 100%;
  left: 0px;
  right: 0px;
}
.login-box .social {
  display: block;
  margin-bottom: 30px;
}

#recoverform {
  display: none;
}

.login-sidebar {
  padding: 0px;
  margin-top: 0px;
}
.login-sidebar .login-box {
  right: 0px;
  position: absolute;
  height: 100%;
}
</style>
